# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric (https://fabricmc.net/develop)
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod
version=1.0.0
group=com.selectiverendering
archives_base_name=selective-rendering
